version: '3.7'

services:
  # tudo que for dependência da aplicação, virá antes de declarar a aplicação.
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite
# Referência para o pgdata
volumes:
  pgdata:
    driver: local
